// Generated by tooling/webgpu/port-shaders.mjs; edit GLSL source, then regenerate.
diagnostic(off, derivative_uniformity);
struct Params {
    data: array<vec4<f32>, 40>,
}

struct FragmentOutput {
    @location(0) outputColor: vec4<f32>,
}

@group(0) @binding(0)
var<uniform> params: Params;
@group(0) @binding(1)
var iChannel0Texture: texture_2d<f32>;
@group(0) @binding(2)
var iChannel0Sampler: sampler;
var<private> outputColor: vec4<f32>;
var<private> gl_FragCoord_1: vec4<f32>;

fn ColorFetch(coord: vec2<f32>) -> vec3<f32> {
    var coord_1: vec2<f32>;

    coord_1 = coord;
    let _e4 = coord_1;
    let _e8 = coord_1;
    let _e13 = coord_1;
    let _e18 = coord_1;
    if ((((_e4.x < 0.00001f) || (_e8.x > 0.99999f)) || (_e13.y < 0.00001f)) || (_e18.y > 0.99999f)) {
        {
            return vec3(0f);
        }
    }
    let _e25 = coord_1;
    let _e26 = textureSample(iChannel0Texture, iChannel0Sampler, _e25);
    return _e26.xyz;
}

fn Grab1_(coord_2: vec2<f32>, octave: f32, offset: vec2<f32>) -> vec3<f32> {
    var coord_3: vec2<f32>;
    var octave_1: f32;
    var offset_1: vec2<f32>;
    var scale: f32;

    coord_3 = coord_2;
    octave_1 = octave;
    offset_1 = offset;
    let _e6 = octave_1;
    scale = exp2(_e6);
    let _e9 = coord_3;
    let _e10 = offset_1;
    coord_3 = (_e9 + _e10);
    let _e12 = coord_3;
    let _e13 = scale;
    coord_3 = (_e12 * _e13);
    let _e15 = coord_3;
    let _e19 = coord_3;
    let _e24 = coord_3;
    let _e29 = coord_3;
    if ((((_e15.x < 0f) || (_e19.x > 1f)) || (_e24.y < 0f)) || (_e29.y > 1f)) {
        {
            return vec3(0f);
        }
    }
    let _e36 = coord_3;
    let _e37 = ColorFetch(_e36);
    return _e37;
}

fn SampleBloomFootprint(coord_4: vec2<f32>, scale_1: f32) -> vec3<f32> {
    var coord_5: vec2<f32>;
    var scale_2: f32;
    var radius: vec2<f32>;
    var color: vec3<f32>;

    coord_5 = coord_4;
    scale_2 = scale_1;
    let _e5 = scale_2;
    let _e8 = params.data[0];
    radius = (vec2(_e5) / _e8.xy);
    let _e13 = coord_5;
    let _e14 = ColorFetch(_e13);
    color = (_e14 * 0.25f);
    let _e18 = color;
    let _e19 = coord_5;
    let _e20 = radius;
    let _e26 = ColorFetch((_e19 + (_e20 * vec2<f32>(1f, 0f))));
    color = (_e18 + (_e26 * 0.1f));
    let _e30 = color;
    let _e31 = coord_5;
    let _e32 = radius;
    let _e38 = ColorFetch((_e31 + (_e32 * vec2<f32>(-1f, 0f))));
    color = (_e30 + (_e38 * 0.1f));
    let _e42 = color;
    let _e43 = coord_5;
    let _e44 = radius;
    let _e50 = ColorFetch((_e43 + (_e44 * vec2<f32>(0f, 1f))));
    color = (_e42 + (_e50 * 0.1f));
    let _e54 = color;
    let _e55 = coord_5;
    let _e56 = radius;
    let _e62 = ColorFetch((_e55 + (_e56 * vec2<f32>(0f, -1f))));
    color = (_e54 + (_e62 * 0.1f));
    let _e66 = color;
    let _e67 = coord_5;
    let _e68 = radius;
    let _e74 = ColorFetch((_e67 + (_e68 * vec2<f32>(0.7f, 0.7f))));
    color = (_e66 + (_e74 * 0.0875f));
    let _e78 = color;
    let _e79 = coord_5;
    let _e80 = radius;
    let _e86 = ColorFetch((_e79 + (_e80 * vec2<f32>(-0.7f, 0.7f))));
    color = (_e78 + (_e86 * 0.0875f));
    let _e90 = color;
    let _e91 = coord_5;
    let _e92 = radius;
    let _e98 = ColorFetch((_e91 + (_e92 * vec2<f32>(0.7f, -0.7f))));
    color = (_e90 + (_e98 * 0.0875f));
    let _e102 = color;
    let _e103 = coord_5;
    let _e104 = radius;
    let _e110 = ColorFetch((_e103 + (_e104 * vec2<f32>(-0.7f, -0.7f))));
    color = (_e102 + (_e110 * 0.0875f));
    let _e114 = color;
    return _e114;
}

fn GrabBloomLevel(coord_6: vec2<f32>, octave_2: f32, offset_2: vec2<f32>) -> vec3<f32> {
    var coord_7: vec2<f32>;
    var octave_3: f32;
    var offset_3: vec2<f32>;
    var scale_3: f32;

    coord_7 = coord_6;
    octave_3 = octave_2;
    offset_3 = offset_2;
    let _e6 = octave_3;
    scale_3 = exp2(_e6);
    let _e9 = coord_7;
    let _e10 = offset_3;
    coord_7 = (_e9 + _e10);
    let _e12 = coord_7;
    let _e13 = scale_3;
    coord_7 = (_e12 * _e13);
    let _e15 = coord_7;
    let _e19 = coord_7;
    let _e24 = coord_7;
    let _e29 = coord_7;
    if ((((_e15.x < 0f) || (_e19.x > 1f)) || (_e24.y < 0f)) || (_e29.y > 1f)) {
        {
            return vec3(0f);
        }
    }
    let _e36 = coord_7;
    let _e37 = scale_3;
    let _e38 = SampleBloomFootprint(_e36, _e37);
    return _e38;
}

fn CalcOffset(octave_4: f32) -> vec2<f32> {
    var octave_5: f32;
    var offset_4: vec2<f32> = vec2(0f);
    var padding: vec2<f32>;

    octave_5 = octave_4;
    let _e10 = params.data[0];
    padding = (vec2(10f) / _e10.xy);
    let _e16 = octave_5;
    let _e23 = padding;
    offset_4.x = (-(min(1f, floor((_e16 / 3f)))) * (0.25f + _e23.x));
    let _e30 = octave_5;
    let _e35 = padding;
    let _e37 = octave_5;
    offset_4.y = (-((1f - (1f / exp2(_e30)))) - (_e35.y * _e37));
    let _e41 = offset_4;
    let _e44 = octave_5;
    offset_4.y = (_e41.y + (min(1f, floor((_e44 / 3f))) * 0.35f));
    let _e52 = offset_4;
    return _e52;
}

fn GetMipmapTree(uv: vec2<f32>) -> vec3<f32> {
    var uv_1: vec2<f32>;
    var color_1: vec3<f32> = vec3(0f);

    uv_1 = uv;
    let _e5 = color_1;
    let _e6 = uv_1;
    let _e11 = Grab1_(_e6, 1f, vec2<f32>(0f, 0f));
    color_1 = (_e5 + _e11);
    let _e13 = color_1;
    let _e14 = uv_1;
    let _e17 = CalcOffset(1f);
    let _e19 = GrabBloomLevel(_e14, 2f, vec2<f32>(_e17));
    color_1 = (_e13 + _e19);
    let _e21 = color_1;
    let _e22 = uv_1;
    let _e25 = CalcOffset(2f);
    let _e27 = GrabBloomLevel(_e22, 3f, vec2<f32>(_e25));
    color_1 = (_e21 + _e27);
    let _e29 = color_1;
    let _e30 = uv_1;
    let _e33 = CalcOffset(3f);
    let _e35 = GrabBloomLevel(_e30, 4f, vec2<f32>(_e33));
    color_1 = (_e29 + _e35);
    let _e37 = color_1;
    let _e38 = uv_1;
    let _e41 = CalcOffset(4f);
    let _e43 = GrabBloomLevel(_e38, 5f, vec2<f32>(_e41));
    color_1 = (_e37 + _e43);
    let _e45 = color_1;
    let _e46 = uv_1;
    let _e49 = CalcOffset(5f);
    let _e51 = GrabBloomLevel(_e46, 6f, vec2<f32>(_e49));
    color_1 = (_e45 + _e51);
    let _e53 = color_1;
    let _e54 = uv_1;
    let _e57 = CalcOffset(6f);
    let _e59 = GrabBloomLevel(_e54, 7f, vec2<f32>(_e57));
    color_1 = (_e53 + _e59);
    let _e61 = color_1;
    let _e62 = uv_1;
    let _e65 = CalcOffset(7f);
    let _e67 = GrabBloomLevel(_e62, 8f, vec2<f32>(_e65));
    color_1 = (_e61 + _e67);
    let _e69 = color_1;
    return _e69;
}

fn GaussBlur(uv_2: vec2<f32>, horizontal: bool) -> vec3<f32> {
    var uv_3: vec2<f32>;
    var horizontal_1: bool;
    var weights: array<f32, 5>;
    var offsets: array<f32, 5>;
    var color_2: vec3<f32> = vec3(0f);
    var weightSum: f32 = 0f;
    var local: vec2<f32>;
    var stepDir: vec2<f32>;
    var i: i32 = 1i;
    var offset_5: vec2<f32>;

    uv_3 = uv_2;
    horizontal_1 = horizontal;
    weights[0i] = 0.19638062f;
    weights[1i] = 0.29675293f;
    weights[2i] = 0.09442139f;
    weights[3i] = 0.01037598f;
    weights[4i] = 0.0002594f;
    offsets[0i] = 0f;
    offsets[1i] = 1.4117647f;
    offsets[2i] = 3.2941177f;
    offsets[3i] = 5.1764708f;
    offsets[4i] = 7.0588236f;
    let _e42 = horizontal_1;
    if _e42 {
        local = vec2<f32>(0.5f, 0f);
    } else {
        local = vec2<f32>(0f, 0.5f);
    }
    let _e50 = local;
    stepDir = _e50;
    let _e52 = uv_3;
    if (_e52.x < 0.52f) {
        {
            let _e56 = color_2;
            let _e57 = uv_3;
            let _e58 = ColorFetch(_e57);
            let _e60 = weights[0];
            color_2 = (_e56 + (_e58 * _e60));
            let _e63 = weightSum;
            let _e65 = weights[0];
            weightSum = (_e63 + _e65);
            loop {
                let _e69 = i;
                if !((_e69 < 5i)) {
                    break;
                }
                {
                    let _e76 = i;
                    let _e78 = offsets[_e76];
                    let _e82 = params.data[0];
                    offset_5 = (vec2(_e78) / _e82.xy);
                    let _e86 = color_2;
                    let _e87 = uv_3;
                    let _e88 = offset_5;
                    let _e89 = stepDir;
                    let _e92 = ColorFetch((_e87 + (_e88 * _e89)));
                    let _e93 = i;
                    let _e95 = weights[_e93];
                    color_2 = (_e86 + (_e92 * _e95));
                    let _e98 = color_2;
                    let _e99 = uv_3;
                    let _e100 = offset_5;
                    let _e101 = stepDir;
                    let _e104 = ColorFetch((_e99 - (_e100 * _e101)));
                    let _e105 = i;
                    let _e107 = weights[_e105];
                    color_2 = (_e98 + (_e104 * _e107));
                    let _e110 = weightSum;
                    let _e111 = i;
                    let _e113 = weights[_e111];
                    weightSum = (_e110 + (_e113 * 2f));
                }
                continuing {
                    let _e73 = i;
                    i = (_e73 + 1i);
                }
            }
            let _e117 = color_2;
            let _e118 = weightSum;
            color_2 = (_e117 / vec3(max(_e118, 0.0001f)));
        }
    }
    let _e123 = color_2;
    return _e123;
}

fn mainImage(fragColor: ptr<function, vec4<f32>>, fragCoord: vec2<f32>) {
    var fragCoord_1: vec2<f32>;
    var uv_4: vec2<f32>;

    fragCoord_1 = fragCoord;
    let _e4 = fragCoord_1;
    let _e8 = params.data[0];
    uv_4 = (_e4.xy / _e8.xy);
    let _e14 = params.data[16];
    if (i32(_e14.x) == 0i) {
        {
            let _e19 = uv_4;
            let _e20 = GetMipmapTree(_e19);
            (*fragColor) = vec4<f32>(_e20.x, _e20.y, _e20.z, 1f);
            return;
        }
    } else {
        {
            let _e26 = uv_4;
            let _e29 = params.data[16];
            let _e34 = GaussBlur(_e26, (i32(_e29.x) == 1i));
            (*fragColor) = vec4<f32>(_e34.x, _e34.y, _e34.z, 1f);
            return;
        }
    }
}

fn main_1() {
    var local_1: vec4<f32>;

    let _e2 = gl_FragCoord_1;
    mainImage((&local_1), _e2.xy);
    let _e5 = local_1;
    outputColor = _e5;
    return;
}

@fragment
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e3 = outputColor;
    return FragmentOutput(_e3);
}
