// Generated by tooling/webgpu/port-shaders.mjs; edit GLSL source, then regenerate.
diagnostic(off, derivative_uniformity);
struct Params {
    data: array<vec4<f32>, 40>,
}

struct FragmentOutput {
    @location(0) outputColor: vec4<f32>,
}

@group(0) @binding(0)
var<uniform> params: Params;
@group(0) @binding(1)
var iChannel0Texture: texture_2d<f32>;
@group(0) @binding(2)
var iChannel0Sampler: sampler;
var<private> outputColor: vec4<f32>;
var<private> weights: array<f32, 5>;
var<private> offsets: array<f32, 5>;
var<private> gl_FragCoord_1: vec4<f32>;

fn ColorFetch(coord: vec2<f32>) -> vec3<f32> {
    var coord_1: vec2<f32>;

    coord_1 = coord;
    let _e4 = coord_1;
    let _e5 = textureSample(iChannel0Texture, iChannel0Sampler, _e4);
    return _e5.xyz;
}

fn mainImage(fragColor: ptr<function, vec4<f32>>, fragCoord: vec2<f32>) {
    var fragCoord_1: vec2<f32>;
    var uv: vec2<f32>;
    var color: vec3<f32> = vec3(0f);
    var weightSum: f32 = 0f;
    var i: i32 = 1i;
    var offset: vec2<f32>;

    fragCoord_1 = fragCoord;
    weights[0i] = 0.19638062f;
    weights[1i] = 0.29675293f;
    weights[2i] = 0.09442139f;
    weights[3i] = 0.01037598f;
    weights[4i] = 0.0002594f;
    offsets[0i] = 0f;
    offsets[1i] = 1.4117647f;
    offsets[2i] = 3.2941177f;
    offsets[3i] = 5.1764708f;
    offsets[4i] = 7.0588236f;
    let _e36 = fragCoord_1;
    let _e40 = params.data[0];
    uv = (_e36.xy / _e40.xy);
    let _e49 = uv;
    if (_e49.x < 0.52f) {
        {
            let _e53 = color;
            let _e54 = uv;
            let _e55 = ColorFetch(_e54);
            let _e57 = weights[0];
            color = (_e53 + (_e55 * _e57));
            let _e60 = weightSum;
            let _e62 = weights[0];
            weightSum = (_e60 + _e62);
            loop {
                let _e66 = i;
                if !((_e66 < 5i)) {
                    break;
                }
                {
                    let _e73 = i;
                    let _e75 = offsets[_e73];
                    let _e79 = params.data[0];
                    offset = (vec2(_e75) / _e79.xy);
                    let _e83 = color;
                    let _e84 = uv;
                    let _e85 = offset;
                    let _e91 = ColorFetch((_e84 + (_e85 * vec2<f32>(0f, 0.5f))));
                    let _e92 = i;
                    let _e94 = weights[_e92];
                    color = (_e83 + (_e91 * _e94));
                    let _e97 = color;
                    let _e98 = uv;
                    let _e99 = offset;
                    let _e105 = ColorFetch((_e98 - (_e99 * vec2<f32>(0f, 0.5f))));
                    let _e106 = i;
                    let _e108 = weights[_e106];
                    color = (_e97 + (_e105 * _e108));
                    let _e111 = weightSum;
                    let _e112 = i;
                    let _e114 = weights[_e112];
                    weightSum = (_e111 + (_e114 * 2f));
                }
                continuing {
                    let _e70 = i;
                    i = (_e70 + 1i);
                }
            }
            let _e118 = color;
            let _e119 = weightSum;
            color = (_e118 / vec3(_e119));
        }
    }
    let _e122 = color;
    (*fragColor) = vec4<f32>(_e122.x, _e122.y, _e122.z, 1f);
    return;
}

fn main_1() {
    var local: vec4<f32>;

    let _e2 = gl_FragCoord_1;
    mainImage((&local), _e2.xy);
    let _e5 = local;
    outputColor = _e5;
    return;
}

@fragment
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e3 = outputColor;
    return FragmentOutput(_e3);
}
