// Generated by tooling/webgpu/port-shaders.mjs; edit GLSL source, then regenerate.
diagnostic(off, derivative_uniformity);
struct Params {
    data: array<vec4<f32>, 40>,
}

struct FragmentOutput {
    @location(0) outputColor: vec4<f32>,
}

const CONST_M: f32 = 0.5f;
const KEY_W: i32 = 87i;
const KEY_A: i32 = 65i;
const KEY_S: i32 = 83i;
const KEY_D: i32 = 68i;
const KEY_Q: i32 = 81i;
const KEY_E: i32 = 69i;
const KEY_R: i32 = 82i;
const KEY_F: i32 = 70i;
const MOVE_SPEED: f32 = 2.5f;
const MOUSE_SENSITIVITY: f32 = 0.003f;
const ROLL_SPEED: f32 = 2f;

@group(0) @binding(0)
var<uniform> params: Params;
@group(0) @binding(1)
var iChannel0Texture: texture_2d<f32>;
@group(0) @binding(2)
var iChannel0Sampler: sampler;
var<private> outputColor: vec4<f32>;
var<private> gl_FragCoord_1: vec4<f32>;

fn ColorFetch(coord: vec2<f32>) -> vec3<f32> {
    var coord_1: vec2<f32>;

    coord_1 = coord;
    let _e4 = coord_1;
    let _e5 = textureSample(iChannel0Texture, iChannel0Sampler, _e4);
    return _e5.xyz;
}

fn Grab1_(coord_2: vec2<f32>, octave: f32, offset: vec2<f32>) -> vec3<f32> {
    var coord_3: vec2<f32>;
    var scale: f32;

    coord_3 = coord_2;
    scale = exp2(octave);
    let _e6 = coord_3;
    coord_3 = (_e6 + offset);
    let _e8 = coord_3;
    let _e9 = scale;
    coord_3 = (_e8 * _e9);
    let _e11 = coord_3;
    let _e15 = coord_3;
    let _e20 = coord_3;
    let _e25 = coord_3;
    if ((((_e11.x < 0f) || (_e15.x > 1f)) || (_e20.y < 0f)) || (_e25.y > 1f)) {
        return vec3(0f);
    }
    let _e32 = coord_3;
    let _e33 = ColorFetch(_e32);
    return _e33;
}

fn Grab4_(coord_4: vec2<f32>, octave_1: f32, offset_1: vec2<f32>) -> vec3<f32> {
    var coord_5: vec2<f32>;
    var scale_1: f32;
    var color: vec3<f32> = vec3(0f);
    var weights: f32 = 0f;
    var oversampling: i32 = 4i;
    var i: i32 = 0i;
    var j: i32;
    var off: vec2<f32>;

    coord_5 = coord_4;
    scale_1 = exp2(octave_1);
    let _e7 = coord_5;
    coord_5 = (_e7 + offset_1);
    let _e9 = coord_5;
    let _e10 = scale_1;
    coord_5 = (_e9 * _e10);
    let _e12 = coord_5;
    let _e16 = coord_5;
    let _e21 = coord_5;
    let _e26 = coord_5;
    if ((((_e12.x < 0f) || (_e16.x > 1f)) || (_e21.y < 0f)) || (_e26.y > 1f)) {
        return vec3(0f);
    }
    loop {
        let _e42 = i;
        let _e43 = oversampling;
        if !((_e42 < _e43)) {
            break;
        }
        {
            j = 0i;
            loop {
                let _e51 = j;
                let _e52 = oversampling;
                if !((_e51 < _e52)) {
                    break;
                }
                {
                    let _e58 = i;
                    let _e59 = j;
                    let _e65 = params.data[0];
                    let _e68 = oversampling;
                    let _e76 = params.data[0];
                    let _e80 = scale_1;
                    let _e82 = oversampling;
                    off = ((((vec2<f32>(f32(_e58), f32(_e59)) / _e65.xy) + (vec2((-(f32(_e68)) * 0.5f)) / _e76.xy)) * _e80) / vec2(f32(_e82)));
                    let _e87 = color;
                    let _e88 = coord_5;
                    let _e89 = off;
                    let _e91 = ColorFetch((_e88 + _e89));
                    color = (_e87 + _e91);
                    let _e93 = weights;
                    weights = (_e93 + 1f);
                }
                continuing {
                    let _e55 = j;
                    j = (_e55 + 1i);
                }
            }
        }
        continuing {
            let _e46 = i;
            i = (_e46 + 1i);
        }
    }
    let _e96 = color;
    let _e97 = weights;
    return (_e96 / vec3(_e97));
}

fn Grab8_(coord_6: vec2<f32>, octave_2: f32, offset_2: vec2<f32>) -> vec3<f32> {
    var coord_7: vec2<f32>;
    var scale_2: f32;
    var color_1: vec3<f32> = vec3(0f);
    var weights_1: f32 = 0f;
    var oversampling_1: i32 = 8i;
    var i_1: i32 = 0i;
    var j_1: i32;
    var off_1: vec2<f32>;

    coord_7 = coord_6;
    scale_2 = exp2(octave_2);
    let _e7 = coord_7;
    coord_7 = (_e7 + offset_2);
    let _e9 = coord_7;
    let _e10 = scale_2;
    coord_7 = (_e9 * _e10);
    let _e12 = coord_7;
    let _e16 = coord_7;
    let _e21 = coord_7;
    let _e26 = coord_7;
    if ((((_e12.x < 0f) || (_e16.x > 1f)) || (_e21.y < 0f)) || (_e26.y > 1f)) {
        return vec3(0f);
    }
    loop {
        let _e42 = i_1;
        let _e43 = oversampling_1;
        if !((_e42 < _e43)) {
            break;
        }
        {
            j_1 = 0i;
            loop {
                let _e51 = j_1;
                let _e52 = oversampling_1;
                if !((_e51 < _e52)) {
                    break;
                }
                {
                    let _e58 = i_1;
                    let _e59 = j_1;
                    let _e65 = params.data[0];
                    let _e68 = oversampling_1;
                    let _e76 = params.data[0];
                    let _e80 = scale_2;
                    let _e82 = oversampling_1;
                    off_1 = ((((vec2<f32>(f32(_e58), f32(_e59)) / _e65.xy) + (vec2((-(f32(_e68)) * 0.5f)) / _e76.xy)) * _e80) / vec2(f32(_e82)));
                    let _e87 = color_1;
                    let _e88 = coord_7;
                    let _e89 = off_1;
                    let _e91 = ColorFetch((_e88 + _e89));
                    color_1 = (_e87 + _e91);
                    let _e93 = weights_1;
                    weights_1 = (_e93 + 1f);
                }
                continuing {
                    let _e55 = j_1;
                    j_1 = (_e55 + 1i);
                }
            }
        }
        continuing {
            let _e46 = i_1;
            i_1 = (_e46 + 1i);
        }
    }
    let _e96 = color_1;
    let _e97 = weights_1;
    return (_e96 / vec3(_e97));
}

fn Grab16_(coord_8: vec2<f32>, octave_3: f32, offset_3: vec2<f32>) -> vec3<f32> {
    var coord_9: vec2<f32>;
    var scale_3: f32;
    var color_2: vec3<f32> = vec3(0f);
    var weights_2: f32 = 0f;
    var oversampling_2: i32 = 16i;
    var i_2: i32 = 0i;
    var j_2: i32;
    var off_2: vec2<f32>;

    coord_9 = coord_8;
    scale_3 = exp2(octave_3);
    let _e7 = coord_9;
    coord_9 = (_e7 + offset_3);
    let _e9 = coord_9;
    let _e10 = scale_3;
    coord_9 = (_e9 * _e10);
    let _e12 = coord_9;
    let _e16 = coord_9;
    let _e21 = coord_9;
    let _e26 = coord_9;
    if ((((_e12.x < 0f) || (_e16.x > 1f)) || (_e21.y < 0f)) || (_e26.y > 1f)) {
        return vec3(0f);
    }
    loop {
        let _e42 = i_2;
        let _e43 = oversampling_2;
        if !((_e42 < _e43)) {
            break;
        }
        {
            j_2 = 0i;
            loop {
                let _e51 = j_2;
                let _e52 = oversampling_2;
                if !((_e51 < _e52)) {
                    break;
                }
                {
                    let _e58 = i_2;
                    let _e59 = j_2;
                    let _e65 = params.data[0];
                    let _e68 = oversampling_2;
                    let _e76 = params.data[0];
                    let _e80 = scale_3;
                    let _e82 = oversampling_2;
                    off_2 = ((((vec2<f32>(f32(_e58), f32(_e59)) / _e65.xy) + (vec2((-(f32(_e68)) * 0.5f)) / _e76.xy)) * _e80) / vec2(f32(_e82)));
                    let _e87 = color_2;
                    let _e88 = coord_9;
                    let _e89 = off_2;
                    let _e91 = ColorFetch((_e88 + _e89));
                    color_2 = (_e87 + _e91);
                    let _e93 = weights_2;
                    weights_2 = (_e93 + 1f);
                }
                continuing {
                    let _e55 = j_2;
                    j_2 = (_e55 + 1i);
                }
            }
        }
        continuing {
            let _e46 = i_2;
            i_2 = (_e46 + 1i);
        }
    }
    let _e96 = color_2;
    let _e97 = weights_2;
    return (_e96 / vec3(_e97));
}

fn CalcOffset(octave_4: f32) -> vec2<f32> {
    var octave_5: f32;
    var offset_4: vec2<f32> = vec2(0f);
    var padding: vec2<f32>;

    octave_5 = octave_4;
    let _e10 = params.data[0];
    padding = (vec2(10f) / _e10.xy);
    let _e16 = octave_5;
    let _e23 = padding;
    offset_4.x = (-(min(1f, floor((_e16 / 3f)))) * (0.25f + _e23.x));
    let _e30 = octave_5;
    let _e35 = padding;
    let _e37 = octave_5;
    offset_4.y = (-((1f - (1f / exp2(_e30)))) - (_e35.y * _e37));
    let _e41 = offset_4;
    let _e44 = octave_5;
    offset_4.y = (_e41.y + (min(1f, floor((_e44 / 3f))) * 0.35f));
    let _e52 = offset_4;
    return _e52;
}

fn UpdateCameraState(fragColor: ptr<function, vec4<f32>>, fragCoord: vec2<f32>) {
    var fragCoord_1: vec2<f32>;
    var pxIndex: i32;
    var right: vec3<f32>;
    var up: vec3<f32>;
    var fwd: vec3<f32>;

    fragCoord_1 = fragCoord;
    let _e6 = params.data[0];
    let _e9 = fragCoord_1;
    pxIndex = (i32(_e6.x) - i32(_e9.x));
    let _e16 = params.data[10];
    right = normalize(_e16.xyz);
    let _e22 = params.data[11];
    up = normalize(_e22.xyz);
    let _e26 = right;
    let _e27 = up;
    fwd = normalize(-(cross(_e26, _e27)));
    (*fragColor) = vec4(0f);
    let _e34 = pxIndex;
    if (_e34 == 1i) {
        let _e37 = up;
        (*fragColor) = vec4<f32>(_e37.x, _e37.y, _e37.z, 1f);
    }
    let _e43 = pxIndex;
    if (_e43 == 2i) {
        let _e46 = right;
        (*fragColor) = vec4<f32>(_e46.x, _e46.y, _e46.z, 1f);
    }
    let _e52 = pxIndex;
    if (_e52 == 3i) {
        let _e57 = params.data[9];
        let _e58 = _e57.xyz;
        (*fragColor) = vec4<f32>(_e58.x, _e58.y, _e58.z, 1f);
    }
    let _e64 = pxIndex;
    if (_e64 == 4i) {
        let _e67 = fwd;
        (*fragColor) = vec4<f32>(_e67.x, _e67.y, _e67.z, 1f);
    }
    let _e73 = pxIndex;
    if (_e73 == 5i) {
        let _e78 = params.data[4];
        (*fragColor) = _e78;
    }
    let _e79 = pxIndex;
    if (_e79 == 6i) {
        let _e84 = params.data[1];
        let _e88 = params.data[12];
        (*fragColor) = vec4<f32>(_e84.x, _e88.x, 0f, 1f);
        return;
    } else {
        return;
    }
}

fn mainImage(fragColor_1: ptr<function, vec4<f32>>, fragCoord_2: vec2<f32>) {
    var fragCoord_3: vec2<f32>;
    var isDataPixel: bool;
    var uv: vec2<f32>;
    var color_3: vec3<f32> = vec3(0f);

    fragCoord_3 = fragCoord_2;
    let _e4 = fragCoord_3;
    let _e8 = fragCoord_3;
    let _e12 = params.data[0];
    isDataPixel = ((_e4.y < 1f) && (_e8.x > (_e12.x - 8.5f)));
    let _e19 = isDataPixel;
    if _e19 {
        {
            let _e20 = fragCoord_3;
            UpdateCameraState(fragColor_1, _e20);
            return;
        }
    } else {
        {
            let _e21 = fragCoord_3;
            let _e25 = params.data[0];
            uv = (_e21.xy / _e25.xy);
            let _e32 = color_3;
            let _e33 = uv;
            let _e38 = Grab1_(_e33, 1f, vec2<f32>(0f, 0f));
            color_3 = (_e32 + _e38);
            let _e40 = color_3;
            let _e41 = uv;
            let _e44 = CalcOffset(1f);
            let _e46 = Grab4_(_e41, 2f, vec2<f32>(_e44));
            color_3 = (_e40 + _e46);
            let _e48 = color_3;
            let _e49 = uv;
            let _e52 = CalcOffset(2f);
            let _e54 = Grab8_(_e49, 3f, vec2<f32>(_e52));
            color_3 = (_e48 + _e54);
            let _e56 = color_3;
            let _e57 = uv;
            let _e60 = CalcOffset(3f);
            let _e62 = Grab16_(_e57, 4f, vec2<f32>(_e60));
            color_3 = (_e56 + _e62);
            let _e64 = color_3;
            let _e65 = uv;
            let _e68 = CalcOffset(4f);
            let _e70 = Grab16_(_e65, 5f, vec2<f32>(_e68));
            color_3 = (_e64 + _e70);
            let _e72 = color_3;
            let _e73 = uv;
            let _e76 = CalcOffset(5f);
            let _e78 = Grab16_(_e73, 6f, vec2<f32>(_e76));
            color_3 = (_e72 + _e78);
            let _e80 = color_3;
            let _e81 = uv;
            let _e84 = CalcOffset(6f);
            let _e86 = Grab16_(_e81, 7f, vec2<f32>(_e84));
            color_3 = (_e80 + _e86);
            let _e88 = color_3;
            let _e89 = uv;
            let _e92 = CalcOffset(7f);
            let _e94 = Grab16_(_e89, 8f, vec2<f32>(_e92));
            color_3 = (_e88 + _e94);
            let _e96 = color_3;
            (*fragColor_1) = vec4<f32>(_e96.x, _e96.y, _e96.z, 1f);
            return;
        }
    }
}

fn main_1() {
    var local: vec4<f32>;

    let _e2 = gl_FragCoord_1;
    mainImage((&local), _e2.xy);
    let _e5 = local;
    outputColor = _e5;
    return;
}

@fragment
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e3 = outputColor;
    return FragmentOutput(_e3);
}
