// Generated by tooling/webgpu/port-shaders.mjs; edit GLSL source, then regenerate.
diagnostic(off, derivative_uniformity);
struct Params {
    data: array<vec4<f32>, 40>,
}

struct FragmentOutput {
    @location(0) outputColor: vec4<f32>,
}

@group(0) @binding(0)
var<uniform> params: Params;
@group(0) @binding(1)
var iChannel0Texture: texture_2d<f32>;
@group(0) @binding(2)
var iChannel0Sampler: sampler;
@group(0) @binding(7)
var iChannel3Texture: texture_2d<f32>;
@group(0) @binding(8)
var iChannel3Sampler: sampler;
var<private> outputColor: vec4<f32>;
var<private> gl_FragCoord_1: vec4<f32>;

fn saturate(x: vec3<f32>) -> vec3<f32> {
    var x_1: vec3<f32>;

    x_1 = x;
    let _e2 = x_1;
    return clamp(_e2, vec3(0f), vec3(1f));
}

fn cubic(x_2: f32) -> vec4<f32> {
    var x_3: f32;
    var x2_: f32;
    var x3_: f32;
    var w: vec4<f32>;

    x_3 = x_2;
    let _e2 = x_3;
    let _e3 = x_3;
    x2_ = (_e2 * _e3);
    let _e6 = x2_;
    let _e7 = x_3;
    x3_ = (_e6 * _e7);
    let _e12 = x3_;
    let _e15 = x2_;
    let _e19 = x_3;
    w.x = (((-(_e12) + (3f * _e15)) - (3f * _e19)) + 1f);
    let _e26 = x3_;
    let _e29 = x2_;
    w.y = (((3f * _e26) - (6f * _e29)) + 4f);
    let _e36 = x3_;
    let _e39 = x2_;
    let _e43 = x_3;
    w.z = ((((-3f * _e36) + (3f * _e39)) + (3f * _e43)) + 1f);
    let _e49 = x3_;
    w.w = _e49;
    let _e50 = w;
    return (_e50 / vec4(6f));
}

fn BicubicTexture(coord: vec2<f32>) -> vec4<f32> {
    var coord_1: vec2<f32>;
    var resolution: vec2<f32>;
    var fx: f32;
    var fy: f32;
    var xcubic: vec4<f32>;
    var ycubic: vec4<f32>;
    var c: vec4<f32>;
    var s: vec4<f32>;
    var offset: vec4<f32>;
    var sample0_: vec4<f32>;
    var sample1_: vec4<f32>;
    var sample2_: vec4<f32>;
    var sample3_: vec4<f32>;
    var sx: f32;
    var sy: f32;

    coord_1 = coord;
    let _e5 = textureDimensions(iChannel3Texture, 0i);
    resolution = vec2<f32>(vec2<i32>(_e5));
    let _e9 = coord_1;
    let _e10 = resolution;
    coord_1 = (_e9 * _e10);
    let _e12 = coord_1;
    fx = fract(_e12.x);
    let _e16 = coord_1;
    fy = fract(_e16.y);
    let _e21 = coord_1;
    let _e23 = fx;
    coord_1.x = (_e21.x - _e23);
    let _e26 = coord_1;
    let _e28 = fy;
    coord_1.y = (_e26.y - _e28);
    let _e30 = fx;
    fx = (_e30 - 0.5f);
    let _e33 = fy;
    fy = (_e33 - 0.5f);
    let _e36 = fx;
    let _e37 = cubic(_e36);
    xcubic = _e37;
    let _e39 = fy;
    let _e40 = cubic(_e39);
    ycubic = _e40;
    let _e42 = coord_1;
    let _e46 = coord_1;
    let _e50 = coord_1;
    let _e54 = coord_1;
    c = vec4<f32>((_e42.x - 0.5f), (_e46.x + 1.5f), (_e50.y - 0.5f), (_e54.y + 1.5f));
    let _e60 = xcubic;
    let _e62 = xcubic;
    let _e65 = xcubic;
    let _e67 = xcubic;
    let _e70 = ycubic;
    let _e72 = ycubic;
    let _e75 = ycubic;
    let _e77 = ycubic;
    s = vec4<f32>((_e60.x + _e62.y), (_e65.z + _e67.w), (_e70.x + _e72.y), (_e75.z + _e77.w));
    let _e82 = c;
    let _e83 = xcubic;
    let _e85 = xcubic;
    let _e87 = ycubic;
    let _e89 = ycubic;
    let _e92 = s;
    offset = (_e82 + (vec4<f32>(_e83.y, _e85.w, _e87.y, _e89.w) / _e92));
    let _e96 = offset;
    let _e98 = offset;
    let _e101 = resolution;
    let _e103 = textureSample(iChannel3Texture, iChannel3Sampler, (vec2<f32>(_e96.x, _e98.z) / _e101));
    sample0_ = _e103;
    let _e105 = offset;
    let _e107 = offset;
    let _e110 = resolution;
    let _e112 = textureSample(iChannel3Texture, iChannel3Sampler, (vec2<f32>(_e105.y, _e107.z) / _e110));
    sample1_ = _e112;
    let _e114 = offset;
    let _e116 = offset;
    let _e119 = resolution;
    let _e121 = textureSample(iChannel3Texture, iChannel3Sampler, (vec2<f32>(_e114.x, _e116.w) / _e119));
    sample2_ = _e121;
    let _e123 = offset;
    let _e125 = offset;
    let _e128 = resolution;
    let _e130 = textureSample(iChannel3Texture, iChannel3Sampler, (vec2<f32>(_e123.y, _e125.w) / _e128));
    sample3_ = _e130;
    let _e132 = s;
    let _e134 = s;
    let _e136 = s;
    sx = (_e132.x / (_e134.x + _e136.y));
    let _e141 = s;
    let _e143 = s;
    let _e145 = s;
    sy = (_e141.z / (_e143.z + _e145.w));
    let _e150 = sample3_;
    let _e151 = sample2_;
    let _e152 = sx;
    let _e155 = sample1_;
    let _e156 = sample0_;
    let _e157 = sx;
    let _e160 = sy;
    return mix(mix(_e150, _e151, vec4(_e152)), mix(_e155, _e156, vec4(_e157)), vec4(_e160));
}

fn ColorFetch(coord_2: vec2<f32>) -> vec3<f32> {
    var coord_3: vec2<f32>;

    coord_3 = coord_2;
    let _e4 = coord_3;
    let _e5 = textureSample(iChannel0Texture, iChannel0Sampler, _e4);
    return _e5.xyz;
}

fn BloomFetch(coord_4: vec2<f32>) -> vec3<f32> {
    var coord_5: vec2<f32>;

    coord_5 = coord_4;
    let _e2 = coord_5;
    let _e3 = BicubicTexture(_e2);
    return _e3.xyz;
}

fn Grab(coord_6: vec2<f32>, octave: f32, offset_1: vec2<f32>) -> vec3<f32> {
    var coord_7: vec2<f32>;
    var scale: f32;

    coord_7 = coord_6;
    scale = exp2(octave);
    let _e6 = coord_7;
    let _e7 = scale;
    coord_7 = (_e6 / vec2(_e7));
    let _e10 = coord_7;
    coord_7 = (_e10 - offset_1);
    let _e12 = coord_7;
    let _e13 = BloomFetch(_e12);
    return _e13;
}

fn CalcOffset(octave_1: f32) -> vec2<f32> {
    var octave_2: f32;
    var offset_2: vec2<f32> = vec2(0f);
    var padding: vec2<f32>;

    octave_2 = octave_1;
    let _e9 = textureDimensions(iChannel3Texture, 0i);
    padding = (vec2(10f) / vec2<f32>(vec2<i32>(_e9)));
    let _e16 = octave_2;
    let _e23 = padding;
    offset_2.x = (-(min(1f, floor((_e16 / 3f)))) * (0.25f + _e23.x));
    let _e30 = octave_2;
    let _e35 = padding;
    let _e37 = octave_2;
    offset_2.y = (-((1f - (1f / exp2(_e30)))) - (_e35.y * _e37));
    let _e41 = offset_2;
    let _e44 = octave_2;
    offset_2.y = (_e41.y + (min(1f, floor((_e44 / 3f))) * 0.35f));
    let _e52 = offset_2;
    return _e52;
}

fn GetBloom(coord_8: vec2<f32>) -> vec3<f32> {
    var coord_9: vec2<f32>;
    var bloom: vec3<f32> = vec3(0f);

    coord_9 = coord_8;
    let _e5 = bloom;
    let _e6 = coord_9;
    let _e9 = CalcOffset(0f);
    let _e11 = Grab(_e6, 1f, vec2<f32>(_e9));
    bloom = (_e5 + (_e11 * 1f));
    let _e15 = bloom;
    let _e16 = coord_9;
    let _e19 = CalcOffset(1f);
    let _e21 = Grab(_e16, 2f, vec2<f32>(_e19));
    bloom = (_e15 + (_e21 * 0.7f));
    let _e25 = bloom;
    let _e26 = coord_9;
    let _e29 = CalcOffset(2f);
    let _e31 = Grab(_e26, 3f, vec2<f32>(_e29));
    bloom = (_e25 + (_e31 * 1f));
    let _e35 = bloom;
    let _e36 = coord_9;
    let _e39 = CalcOffset(3f);
    let _e41 = Grab(_e36, 4f, vec2<f32>(_e39));
    bloom = (_e35 + (_e41 * 0.7f));
    let _e45 = bloom;
    let _e46 = coord_9;
    let _e49 = CalcOffset(4f);
    let _e51 = Grab(_e46, 5f, vec2<f32>(_e49));
    bloom = (_e45 + (_e51 * 0.2f));
    let _e55 = bloom;
    let _e56 = coord_9;
    let _e59 = CalcOffset(5f);
    let _e61 = Grab(_e56, 6f, vec2<f32>(_e59));
    bloom = (_e55 + (_e61 * 0.08f));
    let _e65 = bloom;
    let _e66 = coord_9;
    let _e69 = CalcOffset(6f);
    let _e71 = Grab(_e66, 7f, vec2<f32>(_e69));
    bloom = (_e65 + (_e71 * 0.03f));
    let _e75 = bloom;
    let _e76 = coord_9;
    let _e79 = CalcOffset(7f);
    let _e81 = Grab(_e76, 8f, vec2<f32>(_e79));
    bloom = (_e75 + (_e81 * 0.01f));
    let _e85 = bloom;
    return _e85;
}

fn DisplayColor(color: vec3<f32>) -> vec3<f32> {
    var color_1: vec3<f32>;

    color_1 = color;
    let _e2 = color_1;
    color_1 = pow(max(_e2, vec3(0f)), vec3(1.5f));
    let _e9 = color_1;
    let _e11 = color_1;
    color_1 = (_e9 / (vec3(1f) + _e11));
    let _e15 = color_1;
    color_1 = pow(_e15, vec3(0.6666667f));
    let _e19 = color_1;
    let _e20 = color_1;
    let _e24 = color_1;
    color_1 = ((_e19 * _e20) * (vec3(3f) - (2f * _e24)));
    let _e29 = color_1;
    color_1 = pow(_e29, vec3<f32>(1.3f, 1.2f, 1f));
    let _e35 = color_1;
    let _e38 = saturate((_e35 * 1.01f));
    return pow(_e38, vec3(0.3181818f));
}

fn CompositeGlow(base: vec3<f32>, uv: vec2<f32>, sourceColor: vec3<f32>) -> vec3<f32> {
    var base_1: vec3<f32>;
    var uv_1: vec2<f32>;
    var sourceColor_1: vec3<f32>;
    var glow: vec3<f32>;
    var sourcePeak: f32;

    base_1 = base;
    uv_1 = uv;
    sourceColor_1 = sourceColor;
    let _e9 = params.data[28];
    if (_e9.x <= 0f) {
        let _e13 = base_1;
        return _e13;
    }
    let _e14 = uv_1;
    let _e15 = GetBloom(_e14);
    let _e20 = params.data[28];
    let _e25 = params.data[27];
    let _e28 = DisplayColor((((_e15 * 0.018f) * _e20.x) * _e25.x));
    glow = _e28;
    let _e30 = sourceColor_1;
    let _e32 = sourceColor_1;
    let _e35 = sourceColor_1;
    sourcePeak = max(max(_e30.x, _e32.y), _e35.z);
    let _e39 = glow;
    let _e44 = sourcePeak;
    glow = (_e39 * mix(0.035f, 1f, smoothstep(0.04f, 0.45f, _e44)));
    let _e48 = base_1;
    let _e50 = base_1;
    let _e53 = glow;
    return (_e48 + ((vec3(1f) - _e50) * _e53));
}

fn mainImage(fragColor: ptr<function, vec4<f32>>, fragCoord: vec2<f32>) {
    var fragCoord_1: vec2<f32>;
    var uv_2: vec2<f32>;
    var color_2: vec3<f32>;

    fragCoord_1 = fragCoord;
    let _e4 = fragCoord_1;
    let _e8 = params.data[0];
    uv_2 = (_e4.xy / _e8.xy);
    let _e12 = uv_2;
    let _e13 = ColorFetch(_e12);
    let _e16 = params.data[27];
    let _e19 = DisplayColor((_e13 * _e16.x));
    color_2 = _e19;
    let _e23 = params.data[19];
    if (_e23.x <= 0.001f) {
        let _e27 = color_2;
        let _e28 = uv_2;
        let _e29 = color_2;
        let _e30 = CompositeGlow(_e27, _e28, _e29);
        color_2 = _e30;
    }
    let _e31 = color_2;
    (*fragColor) = vec4<f32>(_e31.x, _e31.y, _e31.z, 1f);
    return;
}

fn main_1() {
    var local: vec4<f32>;

    let _e2 = gl_FragCoord_1;
    mainImage((&local), _e2.xy);
    let _e5 = local;
    outputColor = _e5;
    return;
}

@fragment
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e3 = outputColor;
    return FragmentOutput(_e3);
}
