// Offline, reproducible translation only. No compiler is shipped to the browser.
// Install naga-cli 27.0.0 and pass its executable as the first argument.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
const root = new URL("../../", import.meta.url);
const read = (name) =>
	readFileSync(new URL(`shaders/${name}.glsl`, root), "utf8");
const header = read("fragment-header");
const fields = [...header.matchAll(/uniform (?!sampler)(\w+) (\w+)(\[4\])?;/g)];
let slot = 0;
const layout = {};
let prefix =
	"#version 450\nlayout(set=0,binding=0,std140) uniform Params { vec4 data[40]; } params;\n";
for (const [, type, name, array] of fields) {
	layout[name] = slot;
	const access = (n) =>
		`params.data[${n}]${type === "vec4" ? "" : type === "vec3" ? ".xyz" : type === "vec2" ? ".xy" : ".x"}`;
	prefix += `#define ${name} ${array ? `vec3[4](${[0, 1, 2, 3].map((i) => access(slot + i)).join(",")})` : type === "int" ? `int(${access(slot)})` : access(slot)}\n`;
	slot += array ? 4 : 1;
}
for (const [i, name] of [
	"iChannel0",
	"iChannel1",
	"iChannel2",
	"iChannel3",
	"uAsciiAnalysisColor",
	"uAsciiAnalysisState",
].entries()) {
	prefix += `layout(set=0,binding=${1 + i * 2}) uniform texture2D ${name}Texture;\nlayout(set=0,binding=${2 + i * 2}) uniform sampler ${name}Sampler;\n#define ${name} sampler2D(${name}Texture,${name}Sampler)\n`;
}
for (const n of [3, 4])
	prefix += `bvec${n} portIsNan(vec${n} v){return greaterThan(floatBitsToUint(v) & uvec${n}(0x7fffffffu),uvec${n}(0x7f800000u));}\nbvec${n} portIsInf(vec${n} v){return equal(floatBitsToUint(v) & uvec${n}(0x7fffffffu),uvec${n}(0x7f800000u));}\n`;
const temp = mkdtempSync(join(tmpdir(), "black-hole-wgsl-"));
const out = new URL("shaders/webgpu/", root);
mkdirSync(out, { recursive: true });
const image = read("image");
for (const name of [
	"buffer-a",
	"buffer-b",
	"buffer-c",
	"buffer-d",
	"image",
	"ascii",
	"ascii-analysis",
	"cell",
	"bloom",
]) {
	let source =
		name === "ascii"
			? image.slice(0, image.indexOf("void mainImage")) + read("ascii")
			: read(name);
	if (name === "cell")
		source =
			read("buffer-a").slice(
				0,
				read("buffer-a").indexOf("// SECTION 9: mainImage"),
			) +
			read("helpers") +
			source;
	if (name === "buffer-a" || name === "cell")
		source = source
			.replace(/^\s*vec2\s+iResolution\s*=\s*iResolution\.xy;\s*$/m, "")
			.replace(/^#define iPrepass\s+0.*$/m, "#define iPrepass 1")
			.replace(/^#define iQuality\s+1\.0.*$/m, "#define iQuality uQuality")
			.replace(
				/^#define iBlendWeight\s+0\.5.*$/m,
				"#define iBlendWeight uBlendWeight",
			);
	// Naga 27's GLSL frontend drops the left side effect of this comma expression.
	// Expand it into equivalent statements before translation.
	source = source.replace("p -= a, b -= a;", "p -= a; b -= a;");
	// The sole sampler parameter always receives iChannel3; specialize it.
	source = source
		.replace("in sampler2D tex, ", "")
		.replace(/\btex\b/g, "iChannel3")
		.replace("BicubicTexture(iChannel3, coord)", "BicubicTexture(coord)");
	if (name !== "ascii-analysis")
		source =
			"layout(location=0) out vec4 outputColor;\n" +
			source +
			"\nvoid main(){mainImage(outputColor,gl_FragCoord.xy);}\n";
	source = source
		.replace(/\bisnan\(/g, "portIsNan(")
		.replace(/\bisinf\(/g, "portIsInf(");
	const input = join(temp, name + ".frag");
	writeFileSync(input, prefix + source);
	const output = new URL(name + ".wgsl", out);
	execFileSync(
		process.argv[2] || "naga",
		[
			"--input-kind",
			"glsl",
			"--shader-stage",
			"frag",
			"--compact",
			input,
			output.pathname,
		],
		{ stdio: "inherit" },
	);
	let wgsl = readFileSync(output, "utf8");
	// All samples are mip 0 in the original single-level textures. Explicit LOD
	// permits identical sampling within the raymarch's non-uniform control flow.
	// Naga emits textureSample; WGSL uniformity diagnostics are disabled because
	// these textures have one level and derivatives never select another mip.
	wgsl =
		"// Generated by tooling/webgpu/port-shaders.mjs; edit GLSL source, then regenerate.\n" +
		"diagnostic(off, derivative_uniformity);\n" +
		wgsl;
	writeFileSync(output, wgsl.replace(/[ \t]+$/gm, ""));
}
writeFileSync(
	new URL("uniform-layout.json", out),
	JSON.stringify(layout, null, 2) + "\n",
);

const hash = (value) => createHash("sha256").update(value).digest("hex");
const sourceHashes = Object.fromEntries(
	[
		"buffer-a",
		"buffer-b",
		"buffer-c",
		"buffer-d",
		"image",
		"ascii",
		"ascii-analysis",
		"cell",
		"bloom",
	].map((name) => [name, hash(read(name))]),
);
sourceHashes.header = hash(header);
sourceHashes.helpers = hash(
	read("helpers"),
);
writeFileSync(
	new URL("sources.json", out),
	JSON.stringify(
		{ compiler: "naga-cli 27.0.0 (naga 27.0.3)", sourceHashes },
		null,
		2,
	) + "\n",
);
