// Generated by tooling/webgpu/port-shaders.mjs; edit GLSL source, then regenerate.
diagnostic(off, derivative_uniformity);
struct Params {
    data: array<vec4<f32>, 40>,
}

struct FragmentOutput {
    @location(0) cellColor: vec4<f32>,
    @location(1) cellState: vec4<f32>,
}

const LUMA: vec3<f32> = vec3<f32>(0.3f, 0.59f, 0.11f);

@group(0) @binding(0)
var<uniform> params: Params;
@group(0) @binding(1)
var iChannel0Texture: texture_2d<f32>;
@group(0) @binding(2)
var iChannel0Sampler: sampler;
@group(0) @binding(3)
var iChannel1Texture: texture_2d<f32>;
@group(0) @binding(5)
var iChannel2Texture: texture_2d<f32>;
@group(0) @binding(7)
var iChannel3Texture: texture_2d<f32>;
var<private> cellColor: vec4<f32>;
var<private> cellState: vec4<f32>;
var<private> gl_FragCoord_1: vec4<f32>;

fn candidateScore(index: i32, luminance: f32, tangent: vec2<f32>, edge: f32, previous: i32, history: bool) -> f32 {
    var index_1: i32;
    var luminance_1: f32;
    var tangent_1: vec2<f32>;
    var edge_1: f32;
    var previous_1: i32;
    var history_1: bool;
    var metric: vec4<f32>;
    var direction: i32;
    var orientationError: f32 = 0.5f;
    var angle: f32;
    var axis: vec2<f32>;
    var local: f32;

    index_1 = index;
    luminance_1 = luminance;
    tangent_1 = tangent;
    edge_1 = edge;
    previous_1 = previous;
    history_1 = history;
    let _e13 = index_1;
    let _e17 = textureLoad(iChannel2Texture, vec2<i32>(_e13, 0i), 0i);
    metric = _e17;
    let _e19 = metric;
    direction = i32(round((_e19.z * 255f)));
    let _e26 = direction;
    let _e29 = edge_1;
    let _e32 = tangent_1;
    let _e33 = tangent_1;
    if ((_e26 > 0i) && ((_e29 <= 0.28f) || (dot(_e32, _e33) < 0.5f))) {
        return 1000f;
    }
    let _e42 = direction;
    if (_e42 > 0i) {
        {
            let _e45 = direction;
            angle = (f32((_e45 - 1i)) * 0.7853982f);
            let _e52 = angle;
            let _e54 = angle;
            axis = vec2<f32>(cos(_e52), sin(_e54));
            let _e58 = tangent_1;
            let _e59 = axis;
            orientationError = (acos(clamp(abs(dot(_e58, _e59)), 0f, 1f)) / 1.5707964f);
        }
    }
    let _e68 = metric;
    let _e70 = luminance_1;
    let _e76 = edge_1;
    let _e79 = orientationError;
    let _e82 = history_1;
    let _e83 = index_1;
    let _e84 = previous_1;
    if (_e82 && (_e83 != _e84)) {
        local = 0.05f;
    } else {
        local = 0f;
    }
    let _e90 = local;
    return ((abs((_e68.y - _e70)) + ((0.1f * smoothstep(0.28f, 0.5f, _e76)) * _e79)) + _e90);
}

fn main_1() {
    var cell: vec2<i32>;
    var size: vec2<f32>;
    var origin: vec2<f32>;
    var extent: vec2<f32>;
    var local_1: i32;
    var side: i32;
    var values: array<f32, 16>;
    var meanColor: vec3<f32> = vec3(0f);
    var mean: f32 = 0f;
    var square: f32 = 0f;
    var peak: f32 = 0f;
    var minimum: f32 = 1f;
    var halves: vec2<f32> = vec2(0f);
    var y: i32 = 0i;
    var x: i32;
    var offset: vec2<f32>;
    var color: vec3<f32>;
    var lum: f32;
    var local_2: f32;
    var local_3: f32;
    var count: f32;
    var range: f32;
    var variance: f32;
    var varianceNormalized: f32;
    var threshold: f32;
    var occupancy: f32 = 0f;
    var i: i32 = 0i;
    var luminance_2: f32;
    var gradient: vec2<f32>;
    var edge_2: f32;
    var sobel: vec2<f32> = vec2(0f);
    var spacing: vec2<f32>;
    var center: vec2<f32>;
    var y_1: i32 = -1i;
    var x_1: i32;
    var uv: vec2<f32>;
    var lum_1: f32;
    var local_4: f32;
    var local_5: f32;
    var coherence: f32;
    var local_6: vec2<f32>;
    var tangent_2: vec2<f32>;
    var previousState: vec4<f32>;
    var previousLuminance: f32;
    var previous_2: i32;
    var history_2: bool;
    var oldScore: f32;
    var best: i32 = 0i;
    var bestScore: f32 = 1000f;
    var i_1: i32 = 0i;
    var score: f32;
    var local_7: f32;

    let _e9 = gl_FragCoord_1;
    cell = vec2<i32>(_e9.xy);
    let _e15 = params.data[18];
    size = max(_e15.xy, vec2(2f));
    let _e21 = cell;
    let _e23 = size;
    origin = (vec2<f32>(_e21) * _e23);
    let _e26 = size;
    let _e29 = params.data[17];
    let _e31 = origin;
    extent = min(_e26, (_e29.xy - _e31));
    let _e37 = params.data[13];
    if (_e37.x < 0.7f) {
        local_1 = 2i;
    } else {
        local_1 = 4i;
    }
    let _e44 = local_1;
    side = _e44;
    loop {
        let _e63 = y;
        if !((_e63 < 4i)) {
            break;
        }
        x = 0i;
        loop {
            let _e72 = x;
            if !((_e72 < 4i)) {
                break;
            }
            {
                let _e79 = x;
                let _e80 = side;
                let _e82 = y;
                let _e83 = side;
                if ((_e79 >= _e80) || (_e82 >= _e83)) {
                    continue;
                }
                let _e86 = x;
                let _e87 = y;
                let _e94 = side;
                offset = ((vec2<f32>(f32(_e86), f32(_e87)) + vec2(0.5f)) / vec2(f32(_e94)));
                let _e99 = origin;
                let _e100 = offset;
                let _e101 = extent;
                let _e106 = params.data[17];
                let _e109 = textureSample(iChannel0Texture, iChannel0Sampler, ((_e99 + (_e100 * _e101)) / _e106.xy));
                color = _e109.xyz;
                let _e112 = color;
                lum = dot(_e112, LUMA);
                let _e115 = y;
                let _e116 = side;
                let _e118 = x;
                let _e121 = lum;
                values[((_e115 * _e116) + _e118)] = _e121;
                let _e122 = meanColor;
                let _e123 = color;
                meanColor = (_e122 + _e123);
                let _e125 = mean;
                let _e126 = lum;
                mean = (_e125 + _e126);
                let _e128 = square;
                let _e129 = lum;
                let _e130 = lum;
                square = (_e128 + (_e129 * _e130));
                let _e133 = peak;
                let _e134 = lum;
                peak = max(_e133, _e134);
                let _e136 = minimum;
                let _e137 = lum;
                minimum = min(_e136, _e137);
                let _e139 = halves;
                let _e140 = lum;
                let _e141 = x;
                let _e142 = side;
                if (_e141 < (_e142 / 2i)) {
                    local_2 = -1f;
                } else {
                    local_2 = 1f;
                }
                let _e149 = local_2;
                let _e150 = y;
                let _e151 = side;
                if (_e150 < (_e151 / 2i)) {
                    local_3 = -1f;
                } else {
                    local_3 = 1f;
                }
                let _e158 = local_3;
                halves = (_e139 + (_e140 * vec2<f32>(_e149, _e158)));
            }
            continuing {
                let _e76 = x;
                x = (_e76 + 1i);
            }
        }
        continuing {
            let _e67 = y;
            y = (_e67 + 1i);
        }
    }
    let _e162 = side;
    let _e163 = side;
    count = f32((_e162 * _e163));
    let _e167 = meanColor;
    let _e168 = count;
    meanColor = (_e167 / vec3(_e168));
    let _e171 = mean;
    let _e172 = count;
    mean = (_e171 / _e172);
    let _e174 = peak;
    let _e175 = minimum;
    range = (_e174 - _e175);
    let _e179 = square;
    let _e180 = count;
    let _e182 = mean;
    let _e183 = mean;
    variance = max(0f, ((_e179 / _e180) - (_e182 * _e183)));
    let _e189 = variance;
    let _e191 = range;
    let _e192 = range;
    varianceNormalized = clamp(((4f * _e189) / max((_e191 * _e192), 0.0001f)), 0f, 1f);
    let _e201 = mean;
    let _e203 = peak;
    let _e204 = mean;
    threshold = (_e201 + (0.5f * (_e203 - _e204)));
    loop {
        let _e213 = i;
        if !((_e213 < 16i)) {
            break;
        }
        let _e220 = i;
        let _e221 = side;
        let _e222 = side;
        let _e225 = i;
        let _e227 = values[_e225];
        let _e228 = threshold;
        if ((_e220 < (_e221 * _e222)) && (_e227 > _e228)) {
            let _e231 = occupancy;
            let _e233 = count;
            occupancy = (_e231 + (1f / _e233));
        }
        continuing {
            let _e217 = i;
            i = (_e217 + 1i);
        }
    }
    let _e236 = mean;
    let _e240 = varianceNormalized;
    let _e245 = occupancy;
    let _e248 = peak;
    let _e249 = mean;
    luminance_2 = (_e236 + (((0.12f * smoothstep(0.05f, 0.25f, _e240)) * smoothstep(0.2f, 0.6f, _e245)) * (_e248 - _e249)));
    let _e254 = luminance_2;
    let _e259 = params.data[22];
    let _e268 = params.data[21];
    luminance_2 = clamp(((((_e254 - 0.5f) * max(_e259.x, 0.01f)) + 0.5f) + _e268.x), 0f, 1f);
    let _e274 = halves;
    let _e277 = count;
    let _e280 = extent;
    gradient = (((_e274 * 2f) / vec2(_e277)) / max((_e280 * 0.5f), vec2(0.5f)));
    let _e288 = gradient;
    let _e290 = extent;
    let _e292 = extent;
    let _e296 = range;
    edge_2 = clamp(((length(_e288) * min(_e290.x, _e292.y)) / max(_e296, 0.05f)), 0f, 1f);
    let _e307 = size;
    spacing = (_e307 * 0.5f);
    let _e311 = origin;
    let _e312 = extent;
    center = (_e311 + (_e312 * 0.5f));
    loop {
        let _e319 = y_1;
        if !((_e319 <= 1i)) {
            break;
        }
        x_1 = -1i;
        loop {
            let _e328 = x_1;
            if !((_e328 <= 1i)) {
                break;
            }
            {
                let _e335 = center;
                let _e336 = x_1;
                let _e337 = y_1;
                let _e341 = spacing;
                let _e346 = params.data[17];
                uv = clamp(((_e335 + (vec2<f32>(f32(_e336), f32(_e337)) * _e341)) / _e346.xy), vec2(0f), vec2(1f));
                let _e355 = uv;
                let _e356 = textureSample(iChannel0Texture, iChannel0Sampler, _e355);
                lum_1 = dot(_e356.xyz, LUMA);
                let _e360 = sobel;
                let _e361 = lum_1;
                let _e362 = x_1;
                let _e364 = y_1;
                if (_e364 == 0i) {
                    local_4 = 2f;
                } else {
                    local_4 = 1f;
                }
                let _e370 = local_4;
                let _e372 = y_1;
                let _e374 = x_1;
                if (_e374 == 0i) {
                    local_5 = 2f;
                } else {
                    local_5 = 1f;
                }
                let _e380 = local_5;
                sobel = (_e360 + (_e361 * vec2<f32>((f32(_e362) * _e370), (f32(_e372) * _e380))));
            }
            continuing {
                let _e332 = x_1;
                x_1 = (_e332 + 1i);
            }
        }
        continuing {
            let _e323 = y_1;
            y_1 = (_e323 + 1i);
        }
    }
    let _e385 = sobel;
    let _e387 = spacing;
    sobel = (_e385 / (8f * _e387));
    let _e390 = sobel;
    let _e392 = size;
    let _e394 = size;
    let _e398 = range;
    coherence = ((length(_e390) * min(_e392.x, _e394.y)) / max(_e398, 0.05f));
    let _e403 = coherence;
    if (_e403 > 0.02f) {
        let _e406 = sobel;
        let _e409 = sobel;
        local_6 = normalize(vec2<f32>(-(_e406.y), _e409.x));
    } else {
        local_6 = vec2(0f);
    }
    let _e416 = local_6;
    tangent_2 = _e416;
    let _e418 = cell;
    let _e420 = textureLoad(iChannel1Texture, _e418, 0i);
    previousState = _e420;
    let _e422 = cell;
    let _e424 = textureLoad(iChannel3Texture, _e422, 0i);
    previousLuminance = _e424.w;
    let _e427 = previousState;
    previous_2 = i32(round((_e427.x * 255f)));
    let _e436 = params.data[3];
    let _e441 = previous_2;
    let _e444 = params.data[20];
    let _e449 = luminance_2;
    let _e450 = previousLuminance;
    history_2 = (((i32(_e436.x) > 0i) && (_e441 < i32(_e444.x))) && (abs((_e449 - _e450)) <= 0.12f));
    let _e457 = previous_2;
    let _e458 = luminance_2;
    let _e459 = tangent_2;
    let _e460 = edge_2;
    let _e461 = previous_2;
    let _e463 = candidateScore(_e457, _e458, _e459, _e460, _e461, false);
    oldScore = _e463;
    let _e465 = history_2;
    let _e466 = oldScore;
    history_2 = (_e465 && (_e466 < 999f));
    loop {
        let _e476 = i_1;
        if !((_e476 < 96i)) {
            break;
        }
        {
            let _e483 = i_1;
            let _e486 = params.data[20];
            if (_e483 >= i32(_e486.x)) {
                break;
            }
            let _e490 = i_1;
            let _e491 = luminance_2;
            let _e492 = tangent_2;
            let _e493 = edge_2;
            let _e494 = previous_2;
            let _e495 = history_2;
            let _e496 = candidateScore(_e490, _e491, _e492, _e493, _e494, _e495);
            score = _e496;
            let _e498 = score;
            let _e499 = bestScore;
            if (_e498 < _e499) {
                {
                    let _e501 = i_1;
                    best = _e501;
                    let _e502 = score;
                    bestScore = _e502;
                }
            }
        }
        continuing {
            let _e480 = i_1;
            i_1 = (_e480 + 1i);
        }
    }
    let _e503 = history_2;
    let _e504 = oldScore;
    let _e505 = bestScore;
    let _e509 = oldScore;
    let _e510 = bestScore;
    let _e512 = oldScore;
    if (_e503 && (((_e504 - _e505) < 0.005f) || ((_e509 - _e510) < (_e512 * 0.08f)))) {
        let _e518 = previous_2;
        best = _e518;
    }
    let _e519 = peak;
    if (_e519 < 0.02f) {
        best = 0i;
    }
    let _e523 = meanColor;
    let _e524 = luminance_2;
    cellColor = vec4<f32>(_e523.x, _e523.y, _e523.z, _e524);
    let _e529 = best;
    let _e535 = edge_2;
    let _e537 = occupancy;
    let _e538 = peak;
    if (_e538 < 0.02f) {
        local_7 = 0f;
    } else {
        local_7 = 1f;
    }
    let _e544 = local_7;
    cellState = vec4<f32>((f32(_e529) / 255f), smoothstep(0.15f, 0.35f, _e535), _e537, _e544);
    return;
}

@fragment
fn main(@builtin(position) gl_FragCoord: vec4<f32>) -> FragmentOutput {
    gl_FragCoord_1 = gl_FragCoord;
    main_1();
    let _e3 = cellColor;
    let _e5 = cellState;
    return FragmentOutput(_e3, _e5);
}
